services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5442:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres_db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres_db: