server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bank-card-management-system

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres_user:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/migrations/db.migrations.yaml

jwt:
  secret-key: ofNpNhgC7WezuwNHcPbdpDBdS4YEvwsBCJIf8ZWw5s8

  access-token:
    expiration: 1200000

  refresh-token:
    expiration: 2592000000

app:
  admin:
    username: admin
    password: admin