server:
  port: 8080

spring:
  application:
    name: bank-card-management-system

  datasource:
    url: jdbc:postgresql://localhost:5442/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/migrations/db.migrations.yaml

jwt:
  secret-key: ofNpNhgC7WezuwNHcPbdpDBdS4YEvwsBCJIf8ZWw5s8

  access-token:
    expiration: 3600000

  refresh-token:
    expiration: 2592000000